url: ""
baseurl: ""
title: "CI-CSE"
tagline: "Constructor Insitute Chair of Software Engineering"
description: >-
  Website of the Chair of Software Engineering at Constructor Institute.
  Latest news about our research and projects.

cicse:
  bar_link: false

theme: jekyll-theme-cicse

liquid:
  error_mode: strict
  strict_filters: true

plugins:
  - jekyll-postcss-v2

postcss:
  cache: false

exclude:
  - jekyll-theme-cicse
  - README.md
  - postcss.config.js
  - package.json
  - yarn.lock
  - tailwind.config.js
  - LICENSE
